import {MigrationInterface, QueryRunner} from "typeorm";

export class categoryToType1664185058703 implements MigrationInterface {
    name = 'categoryToType1664185058703'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`mentions\` DROP COLUMN \`type\``);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` CHANGE \`id\` \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` CHANGE \`id\` \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` DROP COLUMN \`loggedInAt\``);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`mentions\` ADD \`category\` enum ('chat', 'dm', 'system') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` ADD \`loggedInAt\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` ADD PRIMARY KEY (\`WorkspaceId\`, \`UserId\`)`);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` ADD PRIMARY KEY (\`ChannelId\`, \`UserId\`)`);
        await queryRunner.query(`ALTER TABLE \`dms\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`dms\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`dms\` ADD \`id\` int NOT NULL PRIMARY KEY AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`dms\` DROP COLUMN \`content\``);
        await queryRunner.query(`ALTER TABLE \`dms\` ADD \`content\` text NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`dms\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`dms\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`dms\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`dms\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`dms\` CHANGE \`WorkspaceId\` \`WorkspaceId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`dms\` CHANGE \`SenderId\` \`SenderId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`dms\` CHANGE \`ReceiverId\` \`ReceiverId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`mentions\` CHANGE \`ChatId\` \`ChatId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`mentions\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`mentions\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`mentions\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`mentions\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`mentions\` CHANGE \`WorkspaceId\` \`WorkspaceId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`mentions\` CHANGE \`SenderId\` \`SenderId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`mentions\` CHANGE \`ReceiverId\` \`ReceiverId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` CHANGE \`WorkspaceId\` \`WorkspaceId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` CHANGE \`UserId\` \`UserId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`workspaces\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`workspaces\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`workspaces\` ADD \`id\` int NOT NULL PRIMARY KEY AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`workspaces\` CHANGE \`name\` \`name\` varchar(30) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`workspaces\` ADD UNIQUE INDEX \`IDX_de659ece27e93d8fe29339d0a4\` (\`name\`)`);
        await queryRunner.query(`ALTER TABLE \`workspaces\` CHANGE \`url\` \`url\` varchar(30) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`workspaces\` ADD UNIQUE INDEX \`IDX_22a04f0c0bf6ffd5961a28f5b7\` (\`url\`)`);
        await queryRunner.query(`ALTER TABLE \`workspaces\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`workspaces\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`workspaces\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`workspaces\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`workspaces\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`workspaces\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`workspaces\` CHANGE \`OwnerId\` \`OwnerId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`channels\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`channels\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`channels\` ADD \`id\` int NOT NULL PRIMARY KEY AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`channels\` CHANGE \`name\` \`name\` varchar(30) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`channels\` CHANGE \`private\` \`private\` tinyint(1) NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`channels\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`channels\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`channels\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`channels\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`channels\` CHANGE \`WorkspaceId\` \`WorkspaceId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` CHANGE \`ChannelId\` \`ChannelId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` CHANGE \`UserId\` \`UserId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`id\` int NOT NULL PRIMARY KEY AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`email\` \`email\` varchar(30) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`nickname\` \`nickname\` varchar(30) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`password\` \`password\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`channelchats\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`channelchats\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`channelchats\` ADD \`id\` int NOT NULL PRIMARY KEY AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`channelchats\` DROP COLUMN \`content\``);
        await queryRunner.query(`ALTER TABLE \`channelchats\` ADD \`content\` text NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`channelchats\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`channelchats\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`channelchats\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`channelchats\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`channelchats\` CHANGE \`UserId\` \`UserId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`channelchats\` CHANGE \`ChannelId\` \`ChannelId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` CHANGE \`UserId\` \`UserId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` CHANGE \`WorkspaceId\` \`WorkspaceId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` CHANGE \`UserId\` \`UserId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` CHANGE \`ChannelId\` \`ChannelId\` int NOT NULL`);
        await queryRunner.query(`CREATE INDEX \`dms_ibfk_3\` ON \`dms\` (\`ReceiverId\`)`);
        await queryRunner.query(`CREATE INDEX \`dms_ibfk_2\` ON \`dms\` (\`SenderId\`)`);
        await queryRunner.query(`CREATE INDEX \`WorkspaceId\` ON \`dms\` (\`WorkspaceId\`)`);
        await queryRunner.query(`CREATE INDEX \`ReceiverId\` ON \`mentions\` (\`ReceiverId\`)`);
        await queryRunner.query(`CREATE INDEX \`SenderId\` ON \`mentions\` (\`SenderId\`)`);
        await queryRunner.query(`CREATE INDEX \`WorkspaceId\` ON \`mentions\` (\`WorkspaceId\`)`);
        await queryRunner.query(`CREATE INDEX \`UserId\` ON \`workspacemembers\` (\`UserId\`)`);
        await queryRunner.query(`CREATE INDEX \`OwnerId\` ON \`workspaces\` (\`OwnerId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`url\` ON \`workspaces\` (\`url\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`name\` ON \`workspaces\` (\`name\`)`);
        await queryRunner.query(`CREATE INDEX \`WorkspaceId\` ON \`channels\` (\`WorkspaceId\`)`);
        await queryRunner.query(`CREATE INDEX \`UserId\` ON \`channelmembers\` (\`UserId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`email\` ON \`users\` (\`email\`)`);
        await queryRunner.query(`CREATE INDEX \`ChannelId\` ON \`channelchats\` (\`ChannelId\`)`);
        await queryRunner.query(`CREATE INDEX \`UserId\` ON \`channelchats\` (\`UserId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_1f3af49b8195937f52d3a66e56\` ON \`workspacemembers\` (\`UserId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_77afc26dfe5a8633e6ce35eaa4\` ON \`workspacemembers\` (\`WorkspaceId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_3446cc443ce59a7f7ae62acc16\` ON \`channelmembers\` (\`UserId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_e53905ed6170fb65083051881e\` ON \`channelmembers\` (\`ChannelId\`)`);
        await queryRunner.query(`ALTER TABLE \`dms\` ADD CONSTRAINT \`FK_904b6c6393befe39400ad9ff29c\` FOREIGN KEY (\`WorkspaceId\`) REFERENCES \`workspaces\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`dms\` ADD CONSTRAINT \`FK_e0b2f87fa1167f44f12aea6f5ca\` FOREIGN KEY (\`SenderId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`dms\` ADD CONSTRAINT \`FK_ccb84506be7d2dcb3df1163e8ac\` FOREIGN KEY (\`ReceiverId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`mentions\` ADD CONSTRAINT \`FK_51792a8377dc294a53b2bf7b213\` FOREIGN KEY (\`WorkspaceId\`) REFERENCES \`workspaces\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`mentions\` ADD CONSTRAINT \`FK_f2a3d51cdda2918df6295336ebb\` FOREIGN KEY (\`SenderId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`mentions\` ADD CONSTRAINT \`FK_9cdbb618081d505406bde0e248e\` FOREIGN KEY (\`ReceiverId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` ADD CONSTRAINT \`FK_77afc26dfe5a8633e6ce35eaa44\` FOREIGN KEY (\`WorkspaceId\`) REFERENCES \`workspaces\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` ADD CONSTRAINT \`FK_1f3af49b8195937f52d3a66e566\` FOREIGN KEY (\`UserId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`workspaces\` ADD CONSTRAINT \`FK_d9a20240a57a1c75e626ef56b2f\` FOREIGN KEY (\`OwnerId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`channels\` ADD CONSTRAINT \`FK_9fb12216c2d8cac3fad686e293b\` FOREIGN KEY (\`WorkspaceId\`) REFERENCES \`workspaces\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` ADD CONSTRAINT \`FK_e53905ed6170fb65083051881e7\` FOREIGN KEY (\`ChannelId\`) REFERENCES \`channels\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` ADD CONSTRAINT \`FK_3446cc443ce59a7f7ae62acc168\` FOREIGN KEY (\`UserId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`channelchats\` ADD CONSTRAINT \`FK_d94a7a11d2bc17e56ed7c9790c3\` FOREIGN KEY (\`UserId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`channelchats\` ADD CONSTRAINT \`FK_8494e7d49237c46d648fbab8cf4\` FOREIGN KEY (\`ChannelId\`) REFERENCES \`channels\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`channelchats\` DROP FOREIGN KEY \`FK_8494e7d49237c46d648fbab8cf4\``);
        await queryRunner.query(`ALTER TABLE \`channelchats\` DROP FOREIGN KEY \`FK_d94a7a11d2bc17e56ed7c9790c3\``);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` DROP FOREIGN KEY \`FK_3446cc443ce59a7f7ae62acc168\``);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` DROP FOREIGN KEY \`FK_e53905ed6170fb65083051881e7\``);
        await queryRunner.query(`ALTER TABLE \`channels\` DROP FOREIGN KEY \`FK_9fb12216c2d8cac3fad686e293b\``);
        await queryRunner.query(`ALTER TABLE \`workspaces\` DROP FOREIGN KEY \`FK_d9a20240a57a1c75e626ef56b2f\``);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` DROP FOREIGN KEY \`FK_1f3af49b8195937f52d3a66e566\``);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` DROP FOREIGN KEY \`FK_77afc26dfe5a8633e6ce35eaa44\``);
        await queryRunner.query(`ALTER TABLE \`mentions\` DROP FOREIGN KEY \`FK_9cdbb618081d505406bde0e248e\``);
        await queryRunner.query(`ALTER TABLE \`mentions\` DROP FOREIGN KEY \`FK_f2a3d51cdda2918df6295336ebb\``);
        await queryRunner.query(`ALTER TABLE \`mentions\` DROP FOREIGN KEY \`FK_51792a8377dc294a53b2bf7b213\``);
        await queryRunner.query(`ALTER TABLE \`dms\` DROP FOREIGN KEY \`FK_ccb84506be7d2dcb3df1163e8ac\``);
        await queryRunner.query(`ALTER TABLE \`dms\` DROP FOREIGN KEY \`FK_e0b2f87fa1167f44f12aea6f5ca\``);
        await queryRunner.query(`ALTER TABLE \`dms\` DROP FOREIGN KEY \`FK_904b6c6393befe39400ad9ff29c\``);
        await queryRunner.query(`DROP INDEX \`IDX_e53905ed6170fb65083051881e\` ON \`channelmembers\``);
        await queryRunner.query(`DROP INDEX \`IDX_3446cc443ce59a7f7ae62acc16\` ON \`channelmembers\``);
        await queryRunner.query(`DROP INDEX \`IDX_77afc26dfe5a8633e6ce35eaa4\` ON \`workspacemembers\``);
        await queryRunner.query(`DROP INDEX \`IDX_1f3af49b8195937f52d3a66e56\` ON \`workspacemembers\``);
        await queryRunner.query(`DROP INDEX \`UserId\` ON \`channelchats\``);
        await queryRunner.query(`DROP INDEX \`ChannelId\` ON \`channelchats\``);
        await queryRunner.query(`DROP INDEX \`email\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`UserId\` ON \`channelmembers\``);
        await queryRunner.query(`DROP INDEX \`WorkspaceId\` ON \`channels\``);
        await queryRunner.query(`DROP INDEX \`name\` ON \`workspaces\``);
        await queryRunner.query(`DROP INDEX \`url\` ON \`workspaces\``);
        await queryRunner.query(`DROP INDEX \`OwnerId\` ON \`workspaces\``);
        await queryRunner.query(`DROP INDEX \`UserId\` ON \`workspacemembers\``);
        await queryRunner.query(`DROP INDEX \`WorkspaceId\` ON \`mentions\``);
        await queryRunner.query(`DROP INDEX \`SenderId\` ON \`mentions\``);
        await queryRunner.query(`DROP INDEX \`ReceiverId\` ON \`mentions\``);
        await queryRunner.query(`DROP INDEX \`WorkspaceId\` ON \`dms\``);
        await queryRunner.query(`DROP INDEX \`dms_ibfk_2\` ON \`dms\``);
        await queryRunner.query(`DROP INDEX \`dms_ibfk_3\` ON \`dms\``);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` CHANGE \`ChannelId\` \`ChannelId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` CHANGE \`UserId\` \`UserId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` CHANGE \`WorkspaceId\` \`WorkspaceId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` CHANGE \`UserId\` \`UserId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`channelchats\` CHANGE \`ChannelId\` \`ChannelId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`channelchats\` CHANGE \`UserId\` \`UserId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`channelchats\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`channelchats\` ADD \`updatedAt\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`channelchats\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`channelchats\` ADD \`createdAt\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`channelchats\` DROP COLUMN \`content\``);
        await queryRunner.query(`ALTER TABLE \`channelchats\` ADD \`content\` varchar(30) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`channelchats\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`channelchats\` ADD \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`channelchats\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`deletedAt\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`updatedAt\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`createdAt\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`password\` \`password\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`nickname\` \`nickname\` varchar(30) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\``);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`email\` \`email\` varchar(30) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` CHANGE \`UserId\` \`UserId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` CHANGE \`ChannelId\` \`ChannelId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`channels\` CHANGE \`WorkspaceId\` \`WorkspaceId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`channels\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`channels\` ADD \`updatedAt\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`channels\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`channels\` ADD \`createdAt\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`channels\` CHANGE \`private\` \`private\` tinyint(4) NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`channels\` CHANGE \`name\` \`name\` varchar(30) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`channels\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`channels\` ADD \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`channels\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`workspaces\` CHANGE \`OwnerId\` \`OwnerId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`workspaces\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`workspaces\` ADD \`deletedAt\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`workspaces\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`workspaces\` ADD \`updatedAt\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`workspaces\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`workspaces\` ADD \`createdAt\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`workspaces\` DROP INDEX \`IDX_22a04f0c0bf6ffd5961a28f5b7\``);
        await queryRunner.query(`ALTER TABLE \`workspaces\` CHANGE \`url\` \`url\` varchar(30) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`workspaces\` DROP INDEX \`IDX_de659ece27e93d8fe29339d0a4\``);
        await queryRunner.query(`ALTER TABLE \`workspaces\` CHANGE \`name\` \`name\` varchar(30) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`workspaces\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`workspaces\` ADD \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`workspaces\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` CHANGE \`UserId\` \`UserId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` CHANGE \`WorkspaceId\` \`WorkspaceId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`mentions\` CHANGE \`ReceiverId\` \`ReceiverId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`mentions\` CHANGE \`SenderId\` \`SenderId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`mentions\` CHANGE \`WorkspaceId\` \`WorkspaceId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`mentions\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`mentions\` ADD \`updatedAt\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`mentions\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`mentions\` ADD \`createdAt\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`mentions\` CHANGE \`ChatId\` \`ChatId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dms\` CHANGE \`ReceiverId\` \`ReceiverId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dms\` CHANGE \`SenderId\` \`SenderId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dms\` CHANGE \`WorkspaceId\` \`WorkspaceId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dms\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`dms\` ADD \`updatedAt\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dms\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`dms\` ADD \`createdAt\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dms\` DROP COLUMN \`content\``);
        await queryRunner.query(`ALTER TABLE \`dms\` ADD \`content\` varchar(30) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dms\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`dms\` ADD \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`dms\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` DROP COLUMN \`loggedInAt\``);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`mentions\` DROP COLUMN \`category\``);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` ADD \`updatedAt\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` ADD \`createdAt\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` ADD \`loggedInAt\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` ADD \`updatedAt\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` ADD \`createdAt\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` ADD \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` ADD \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`mentions\` ADD \`type\` enum ('chat', 'dm', 'system') NOT NULL`);
    }

}
