import {MigrationInterface, QueryRunner} from "typeorm";

export class categoryToType1667193407803 implements MigrationInterface {
    name = 'categoryToType1667193407803'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` DROP FOREIGN KEY \`FK_77afc26dfe5a8633e6ce35eaa44\``);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` DROP FOREIGN KEY \`FK_e53905ed6170fb65083051881e7\``);
        await queryRunner.query(`DROP INDEX \`IDX_1f3af49b8195937f52d3a66e56\` ON \`workspacemembers\``);
        await queryRunner.query(`DROP INDEX \`IDX_77afc26dfe5a8633e6ce35eaa4\` ON \`workspacemembers\``);
        await queryRunner.query(`DROP INDEX \`IDX_3446cc443ce59a7f7ae62acc16\` ON \`channelmembers\``);
        await queryRunner.query(`DROP INDEX \`IDX_e53905ed6170fb65083051881e\` ON \`channelmembers\``);
        await queryRunner.query(`DROP INDEX \`UserId\` ON \`workspacemembers\``);
        await queryRunner.query(`DROP INDEX \`UserId\` ON \`channelmembers\``);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` DROP COLUMN \`loggedInAt\``);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` ADD \`loggedInAt\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`dms\` DROP FOREIGN KEY \`FK_904b6c6393befe39400ad9ff29c\``);
        await queryRunner.query(`ALTER TABLE \`dms\` DROP FOREIGN KEY \`FK_e0b2f87fa1167f44f12aea6f5ca\``);
        await queryRunner.query(`ALTER TABLE \`dms\` DROP FOREIGN KEY \`FK_ccb84506be7d2dcb3df1163e8ac\``);
        await queryRunner.query(`ALTER TABLE \`dms\` CHANGE \`WorkspaceId\` \`WorkspaceId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`dms\` CHANGE \`SenderId\` \`SenderId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`dms\` CHANGE \`ReceiverId\` \`ReceiverId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`mentions\` DROP FOREIGN KEY \`FK_51792a8377dc294a53b2bf7b213\``);
        await queryRunner.query(`ALTER TABLE \`mentions\` DROP FOREIGN KEY \`FK_f2a3d51cdda2918df6295336ebb\``);
        await queryRunner.query(`ALTER TABLE \`mentions\` DROP FOREIGN KEY \`FK_9cdbb618081d505406bde0e248e\``);
        await queryRunner.query(`ALTER TABLE \`mentions\` CHANGE \`ChatId\` \`ChatId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`mentions\` CHANGE \`WorkspaceId\` \`WorkspaceId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`mentions\` CHANGE \`SenderId\` \`SenderId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`mentions\` CHANGE \`ReceiverId\` \`ReceiverId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`workspaces\` DROP FOREIGN KEY \`FK_d9a20240a57a1c75e626ef56b2f\``);
        await queryRunner.query(`ALTER TABLE \`workspaces\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`workspaces\` CHANGE \`OwnerId\` \`OwnerId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`channels\` DROP FOREIGN KEY \`FK_9fb12216c2d8cac3fad686e293b\``);
        await queryRunner.query(`ALTER TABLE \`channels\` CHANGE \`WorkspaceId\` \`WorkspaceId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`channelchats\` DROP FOREIGN KEY \`FK_d94a7a11d2bc17e56ed7c9790c3\``);
        await queryRunner.query(`ALTER TABLE \`channelchats\` DROP FOREIGN KEY \`FK_8494e7d49237c46d648fbab8cf4\``);
        await queryRunner.query(`ALTER TABLE \`channelchats\` CHANGE \`UserId\` \`UserId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`channelchats\` CHANGE \`ChannelId\` \`ChannelId\` int NULL`);
        await queryRunner.query(`CREATE INDEX \`UserId\` ON \`workspacemembers\` (\`UserId\`)`);
        await queryRunner.query(`CREATE INDEX \`UserId\` ON \`channelmembers\` (\`UserId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_1f3af49b8195937f52d3a66e56\` ON \`workspacemembers\` (\`UserId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_77afc26dfe5a8633e6ce35eaa4\` ON \`workspacemembers\` (\`WorkspaceId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_3446cc443ce59a7f7ae62acc16\` ON \`channelmembers\` (\`UserId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_e53905ed6170fb65083051881e\` ON \`channelmembers\` (\`ChannelId\`)`);
        await queryRunner.query(`ALTER TABLE \`dms\` ADD CONSTRAINT \`FK_904b6c6393befe39400ad9ff29c\` FOREIGN KEY (\`WorkspaceId\`) REFERENCES \`workspaces\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`dms\` ADD CONSTRAINT \`FK_e0b2f87fa1167f44f12aea6f5ca\` FOREIGN KEY (\`SenderId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`dms\` ADD CONSTRAINT \`FK_ccb84506be7d2dcb3df1163e8ac\` FOREIGN KEY (\`ReceiverId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`mentions\` ADD CONSTRAINT \`FK_51792a8377dc294a53b2bf7b213\` FOREIGN KEY (\`WorkspaceId\`) REFERENCES \`workspaces\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`mentions\` ADD CONSTRAINT \`FK_f2a3d51cdda2918df6295336ebb\` FOREIGN KEY (\`SenderId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`mentions\` ADD CONSTRAINT \`FK_9cdbb618081d505406bde0e248e\` FOREIGN KEY (\`ReceiverId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` ADD CONSTRAINT \`FK_77afc26dfe5a8633e6ce35eaa44\` FOREIGN KEY (\`WorkspaceId\`) REFERENCES \`workspaces\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`workspaces\` ADD CONSTRAINT \`FK_d9a20240a57a1c75e626ef56b2f\` FOREIGN KEY (\`OwnerId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`channels\` ADD CONSTRAINT \`FK_9fb12216c2d8cac3fad686e293b\` FOREIGN KEY (\`WorkspaceId\`) REFERENCES \`workspaces\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` ADD CONSTRAINT \`FK_e53905ed6170fb65083051881e7\` FOREIGN KEY (\`ChannelId\`) REFERENCES \`channels\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`channelchats\` ADD CONSTRAINT \`FK_d94a7a11d2bc17e56ed7c9790c3\` FOREIGN KEY (\`UserId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`channelchats\` ADD CONSTRAINT \`FK_8494e7d49237c46d648fbab8cf4\` FOREIGN KEY (\`ChannelId\`) REFERENCES \`channels\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`channelchats\` DROP FOREIGN KEY \`FK_8494e7d49237c46d648fbab8cf4\``);
        await queryRunner.query(`ALTER TABLE \`channelchats\` DROP FOREIGN KEY \`FK_d94a7a11d2bc17e56ed7c9790c3\``);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` DROP FOREIGN KEY \`FK_e53905ed6170fb65083051881e7\``);
        await queryRunner.query(`ALTER TABLE \`channels\` DROP FOREIGN KEY \`FK_9fb12216c2d8cac3fad686e293b\``);
        await queryRunner.query(`ALTER TABLE \`workspaces\` DROP FOREIGN KEY \`FK_d9a20240a57a1c75e626ef56b2f\``);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` DROP FOREIGN KEY \`FK_77afc26dfe5a8633e6ce35eaa44\``);
        await queryRunner.query(`ALTER TABLE \`mentions\` DROP FOREIGN KEY \`FK_9cdbb618081d505406bde0e248e\``);
        await queryRunner.query(`ALTER TABLE \`mentions\` DROP FOREIGN KEY \`FK_f2a3d51cdda2918df6295336ebb\``);
        await queryRunner.query(`ALTER TABLE \`mentions\` DROP FOREIGN KEY \`FK_51792a8377dc294a53b2bf7b213\``);
        await queryRunner.query(`ALTER TABLE \`dms\` DROP FOREIGN KEY \`FK_ccb84506be7d2dcb3df1163e8ac\``);
        await queryRunner.query(`ALTER TABLE \`dms\` DROP FOREIGN KEY \`FK_e0b2f87fa1167f44f12aea6f5ca\``);
        await queryRunner.query(`ALTER TABLE \`dms\` DROP FOREIGN KEY \`FK_904b6c6393befe39400ad9ff29c\``);
        await queryRunner.query(`DROP INDEX \`IDX_e53905ed6170fb65083051881e\` ON \`channelmembers\``);
        await queryRunner.query(`DROP INDEX \`IDX_3446cc443ce59a7f7ae62acc16\` ON \`channelmembers\``);
        await queryRunner.query(`DROP INDEX \`IDX_77afc26dfe5a8633e6ce35eaa4\` ON \`workspacemembers\``);
        await queryRunner.query(`DROP INDEX \`IDX_1f3af49b8195937f52d3a66e56\` ON \`workspacemembers\``);
        await queryRunner.query(`DROP INDEX \`UserId\` ON \`channelmembers\``);
        await queryRunner.query(`DROP INDEX \`UserId\` ON \`workspacemembers\``);
        await queryRunner.query(`ALTER TABLE \`channelchats\` CHANGE \`ChannelId\` \`ChannelId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`channelchats\` CHANGE \`UserId\` \`UserId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`channelchats\` ADD CONSTRAINT \`FK_8494e7d49237c46d648fbab8cf4\` FOREIGN KEY (\`ChannelId\`) REFERENCES \`channels\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`channelchats\` ADD CONSTRAINT \`FK_d94a7a11d2bc17e56ed7c9790c3\` FOREIGN KEY (\`UserId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`channels\` CHANGE \`WorkspaceId\` \`WorkspaceId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`channels\` ADD CONSTRAINT \`FK_9fb12216c2d8cac3fad686e293b\` FOREIGN KEY (\`WorkspaceId\`) REFERENCES \`workspaces\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`workspaces\` CHANGE \`OwnerId\` \`OwnerId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`workspaces\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`workspaces\` ADD CONSTRAINT \`FK_d9a20240a57a1c75e626ef56b2f\` FOREIGN KEY (\`OwnerId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`mentions\` CHANGE \`ReceiverId\` \`ReceiverId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`mentions\` CHANGE \`SenderId\` \`SenderId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`mentions\` CHANGE \`WorkspaceId\` \`WorkspaceId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`mentions\` CHANGE \`ChatId\` \`ChatId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`mentions\` ADD CONSTRAINT \`FK_9cdbb618081d505406bde0e248e\` FOREIGN KEY (\`ReceiverId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`mentions\` ADD CONSTRAINT \`FK_f2a3d51cdda2918df6295336ebb\` FOREIGN KEY (\`SenderId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`mentions\` ADD CONSTRAINT \`FK_51792a8377dc294a53b2bf7b213\` FOREIGN KEY (\`WorkspaceId\`) REFERENCES \`workspaces\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`dms\` CHANGE \`ReceiverId\` \`ReceiverId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dms\` CHANGE \`SenderId\` \`SenderId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dms\` CHANGE \`WorkspaceId\` \`WorkspaceId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dms\` ADD CONSTRAINT \`FK_ccb84506be7d2dcb3df1163e8ac\` FOREIGN KEY (\`ReceiverId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`dms\` ADD CONSTRAINT \`FK_e0b2f87fa1167f44f12aea6f5ca\` FOREIGN KEY (\`SenderId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`dms\` ADD CONSTRAINT \`FK_904b6c6393befe39400ad9ff29c\` FOREIGN KEY (\`WorkspaceId\`) REFERENCES \`workspaces\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` DROP COLUMN \`loggedInAt\``);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` ADD \`loggedInAt\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`CREATE INDEX \`UserId\` ON \`channelmembers\` (\`UserId\`)`);
        await queryRunner.query(`CREATE INDEX \`UserId\` ON \`workspacemembers\` (\`UserId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_e53905ed6170fb65083051881e\` ON \`channelmembers\` (\`ChannelId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_3446cc443ce59a7f7ae62acc16\` ON \`channelmembers\` (\`UserId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_77afc26dfe5a8633e6ce35eaa4\` ON \`workspacemembers\` (\`WorkspaceId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_1f3af49b8195937f52d3a66e56\` ON \`workspacemembers\` (\`UserId\`)`);
        await queryRunner.query(`ALTER TABLE \`channelmembers\` ADD CONSTRAINT \`FK_e53905ed6170fb65083051881e7\` FOREIGN KEY (\`ChannelId\`) REFERENCES \`channels\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`workspacemembers\` ADD CONSTRAINT \`FK_77afc26dfe5a8633e6ce35eaa44\` FOREIGN KEY (\`WorkspaceId\`) REFERENCES \`workspaces\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
    }

}
